<a href="https://colab.research.google.com/github/anandsubbu007/Pytorch-Tutorial-Beginner/blob/master/Pytorch_Basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch

It’s a Python based scientific computing package targeted at two sets of audiences:

* Tensorial library that uses the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed

# Scope of this Notebook

### In this, we are going to use Pytorch as Numpy.

# Pytorch Vs Numpy

In [0]:
#Importing Library
import torch
import numpy as np

In [0]:
#tuples
lst = ([1,2],[2,3])
print(lst)
print(type(lst))

([1, 2], [2, 3])
<class 'tuple'>


In [0]:
#tuples --> tensor
l = torch.tensor(lst)
print(l)
print(type(l))

tensor([[1, 2],
        [2, 3]])
<class 'torch.Tensor'>


In [0]:
#Numpy --> tensor
l1 = torch.tensor(np.array([1,2,3,4,5]))
print(l1)
print(type(l1))

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>


In [0]:
#Tensor to Numpy
l2 = l1.numpy()
print(l2)
print(type(l2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [0]:
#Other Tensor Formates
print("Empty Tensor    :",torch.tensor([]))
print("Float Tensor    :",torch.tensor([1,2,3],dtype=torch.float))

Empty Tensor    : tensor([])
Float Tensor    : tensor([1., 2., 3.])


## Ways of creaing Tensor array

In [0]:
print("Torch of Ones  :\n",torch.ones(3,3))
print("\nTorch of Zeros :\n",torch.zeros(3,2))
print("\nTorch of Randomn Number :\n",torch.rand(2,3))
print("\nTorch with Range of Number :\n",torch.arange(1,5))
print("\nTorch with Linespace of Number :\n",torch.linspace(1,10,6))
print("\nTorch with Identity Matrix :\n",torch.eye(3))
print("\nTorch with complete Matrix :\n",torch.full((2,3),3))

Torch of Ones  :
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Torch of Zeros :
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Torch of Randomn Number :
 tensor([[0.7680, 0.4237, 0.4676],
        [0.6988, 0.0618, 0.8387]])

Torch with Range of Number :
 tensor([1, 2, 3, 4])

Torch with Linespace of Number :
 tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000])

Torch with Identity Matrix :
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Torch with complete Matrix :
 tensor([[3., 3., 3.],
        [3., 3., 3.]])


## Reshape & Slicing

It is almost similar to reshape & slice in List

#### Reshape tensor (matrix)

There are two way to reshape the tensor using .view & .reshape

* Tensor.view() works only on contiguous tensors and will never copy memory. It will raise an error on a non-contiguous tensor.
* Tensor.reshape() will work on any tensor and can make a clone if it is needed.


In [0]:
l = torch.arange(8)
v = l.view(2,4)
r = l.reshape(4,2)
print("A tensor of range 7 : ", l)
print("\nWhen we use view    \n",v)
print("\nWhen we use Reshape \n",r)
print("\nFind value in tensor using index of value  :  ",v[1,3].item())
print("\nFind value in tensor using index of value  :  ",r[2,0].item())

A tensor of range 7 :  tensor([0, 1, 2, 3, 4, 5, 6, 7])

When we use view    
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

When we use Reshape 
 tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

Find value in tensor using index of value  :   7

Find value in tensor using index of value  :   4


In [0]:
# slicing
print("slicing the tensor  :",l[2:6])
print("slicing the tensor  :",l[:4])

slicing the tensor  : tensor([2, 3, 4, 5])
slicing the tensor  : tensor([0, 1, 2, 3])


## Mathematical Operation on Tensor

In [0]:
x = torch.ones(3,2)
y = torch.full((3,2),3)
print("Tensors of Ones   ,x :\n",x)
print("\nTensors of Full ,y :\n",y)

Tensors of Ones   ,x :
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Tensors of Full ,y :
 tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [0]:
print("Addition of Tensors      , x+y :\n",x+y)
print("\nSubtraction of Tensors   , x-y :\n",x-y)
print("\nMultiplication of Tensors, x*y :\n",x*y)
print("\nDivition of Tensors      , x/y :\n",x/y)

Addition of Tensors      , x+y :
 tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

Subtraction of Tensors   , x-y :
 tensor([[-2., -2.],
        [-2., -2.],
        [-2., -2.]])

Multiplication of Tensors, x*y :
 tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

Divition of Tensors      , x/y :
 tensor([[0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333]])


Torch is around 4 times faster than numpy

# CUDA

CUDA is a parallel computing platform and application programming interface model created by Nvidia.

In [0]:
# IS cuda available in your Device
print("IS cuda available in your Device  ?  : ",torch.cuda.is_available())
print("Count of Available CUDA Device       : ",torch.cuda.device_count())
print("Available Device Name                : ",torch.cuda.get_device_name())

IS cuda available in your Device  ?  :  True
Count of Available CUDA Device       :  1
Available Device Name                :  Tesla K80


In [0]:
#object for cuda device
cuda0 = torch.device('cuda:0')
print("Device used in this  :  ",type(cuda0))
print("\nSample torch with GPU device  :\n",torch.ones(2,2,device =cuda0))

Device used in this  :   <class 'torch.device'>

Sample torch with GPU device  :
 tensor([[1., 1.],
        [1., 1.]], device='cuda:0')


## Performance -  Numpy Vs CPU Tensors Vs GPU Tensors

Computation Time

#### Numpy

In [0]:
%%time
for i in range(1000):
  x = np.random.randn(100,100)
  y = np.random.randn(100,100)
  z = x*y

CPU times: user 869 ms, sys: 4.43 ms, total: 873 ms
Wall time: 877 ms


#### CPU Tensor

In [0]:
%%time
for i in range(1000):
  x = torch.randn(100,100)
  y = torch.randn(100,100)
  z = x*y

CPU times: user 184 ms, sys: 1.08 ms, total: 185 ms
Wall time: 186 ms


#### GPU Tensor

In [0]:
%%time
for i in range(100):
  x = torch.randn(1000,1000,device = cuda0)
  y = torch.randn(1000,1000,device =cuda0)
  z = x*y

CPU times: user 11 ms, sys: 0 ns, total: 11 ms
Wall time: 12.1 ms
